Show progress bar while fitting to training data
automl/auto-sklearn pull request #1606
Opened 2022-11-09 18:26 UTC by barcsin

Closes #1599 

**Motivation:**
Building an AutoML model and calling the fit() function does not give any indication of how much time is left from the optimization process. This may cause confusion especially for fresh users not familiar with the API.

**Solution**
A new class called ProgressBar was added under autosklearn/utils, which is an instance of Thread. By instantiating this thread, it automatically starts itself and displays a (tqdm)[https://tqdm.github.io/docs/tqdm/] progress bar in the console.
ProgressBar gets instantiated at the very beginning of the AutoML fit() method and stopped in the finally block of the outermost try block.

**Controversial**
This feature is automatically on, meaning that the console will show a progress bar by default. However, it can be turned off by setting the newly introduced disable_progress_bar parameter of AutoSklearnEstimator to True.
I believe it is more sensible to have it on by default, since the feature aims to mainly benefit new users and from my experience it greatly improves overall user experience in general.

**Potential introduced bugs**
I noticed that the fit() method doesn't stop after hitting "stop" a single time within my IDE (Pycharm). It requires the "stop" button to be clicked two times to terminate properly.
Nonetheless, I believe this is how autosklearn used to work before I introduced my feature.
This should be clarified and double checked.

2022-11-10 12:46 UTC, eddiebergman commented
> I noticed that the fit() method doesn't always stop after hitting "stop" a single time within my IDE (Pycharm). It requires the "stop" button to be clicked two times to terminate properly.
Nonetheless, I believe this is how autosklearn used to work before I introduced my feature.
This needs further investigation in the future.

For extra context, this stop button in pycharm is the same as `Ctrl+c` and raises a KeyBoardInterrupt which is not handled properly somewhere, suspect it to be SMAC.

2022-11-10 13:30 UTC, eddiebergman requested changes

2022-11-10 13:30 UTC, eddiebergman commented on autosklearn/util/progress_bar.py
> +        disable: flag that turns on or off the progress bar. If false, then no thread is started or created.
We are using numpy docstyle, [check out this portion](https://numpydoc.readthedocs.io/en/latest/format.html#parameters) for how to specify parameters.

2022-11-10 13:30 UTC, eddiebergman commented on autosklearn/util/progress_bar.py
> +        update_interval: reduce this to update the progress bar more frequently
Add that it's in seconds into doc.

2022-11-10 13:30 UTC, eddiebergman commented on autosklearn/util/progress_bar.py
> +    def run(self):
Mypy will warn you but you can specify the return type as such. Mypy has an option that no return type is implicitly None but I'd rather be explicit about it.

```python
def run(self) -> None:
    ...
```

2022-11-10 13:30 UTC, eddiebergman commented on autosklearn/automl.py
> +        progress_bar = ProgressBar(total=self._time_for_task, disable=self.disable_progress_bar)
Put below all validation

2022-11-10 13:30 UTC, eddiebergman commented on autosklearn/estimators.py
> +        self.disable_progress_bar = disable_progress_bar
Also take a look at putting this into `autosklearn.experimental.AutoSklearn2Classifier`

2022-11-11 15:00 UTC, eddiebergman reviewed
Tests are still broken:
* For the test workflows, we discussed that you installing `pytest-forked` worked for you and it seems like we're note really using `pytest-xdist`, we can remove the dependancy for `pytest-xdist` and replace it with `pytest-forked`, you should run it locally with the same arguments and check that it works:
`$PYTHON -m pytest --forked --durations=20 --timeout=600 --timeout-method=thread -s test`
We can later do a PR to utilize more cores if we need.
* You can ignore the doc error for now until we update SMAC.

2022-11-11 15:00 UTC, eddiebergman commented on autosklearn/util/progress_bar.py
> +from tqdm import trange  # type: ignore
Add to ignore in `pyproject.toml`

2022-11-11 15:00 UTC, eddiebergman commented on autosklearn/util/progress_bar.py
> +        """
This could just be shortened onto one line:
```python
def stop(self) -> None:
    """stuff here"""

2022-11-11 15:00 UTC, eddiebergman commented on autosklearn/util/progress_bar.py
> +    A Thread that displays a tqdm progress bar in the console.
Throw this into the short description above.

2022-11-14 08:29 UTC, eddiebergman approved these changes

2022-11-14 08:30 UTC, merged

2023-11-11 16:26 UTC, Proryanator commented
Was this update released into autosklearn? I'm using version `0.15.0` and I'm not seeing any 'progressbar' related code in `autosklearn/automl.py` for example.